name: gaussian_compression
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.0
  - cudatoolkit=11.8
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=11.8
  - plyfile=1.0.3
  - tqdm=4.66.4
  - ipykernel=6.29.3
  - omegaconf=2.3.0
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.5.0
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/tiny-cuda-nn/bindings/torch
